export const  translations = {
    uz: {
        title: "O'zbekiston Mehmonxona Baholash",
        rateHotel: "Mehmonxonani baholash",
        info: "Ma'lumot",
        oneTimeKey: "Bir martalik kalit",
        enterKey: "Kalitni kiriting",
        verify: "Tasdiqlash",
        note: "Eslatma",
        noteText:
            "Mehmonxonadan chiqishda sizga bir martalik kalit beriladi. Shu kalit orqali mehmonxonani baholashingiz mumkin.",
        rateCategories: "Mehmonxonani baholang",
        roomCleanliness: "Xona tozaligi",
        service: "Xizmat ko'rsatish",
        comfort: "Qulaylik",
        food: "Ovqatlanish",
        valueForMoney: "Narx/sifat nisbati",
        comment: "Izoh (ixtiyoriy)",
        commentPlaceholder: "Mehmonxona haqida fikringizni yozing...",
        cancel: "Bekor qilish",
        submit: "Yuborish",
        aboutRating: "Baholash tizimi haqida",
        howItWorks: "O'zbekiston mehmonxona baholash tizimi qanday ishlaydi",
        ratingProcess: "Baholash jarayoni",
        ratingProcessDesc:
            "Mehmonxonadan chiqishda sizga bir martalik maxsus kalit beriladi. Ushbu kalit orqali siz mehmonxonani baholashingiz mumkin. Har bir mijoz faqat bir marta baholash huquqiga ega.",
        ratingCriteria: "Baholash mezonlari",
        ratingCriteriaDesc:
            "Mehmonxonani 1 dan 5 gacha bo'lgan yulduzlar bilan baholashingiz mumkin. Shuningdek, qo'shimcha izoh qoldirishingiz ham mumkin.",
        results: "Natijalar",
        resultsDesc:
            "Barcha baholash natijalari mehmonxona sifatini oshirish uchun foydalaniladi va boshqa mijozlar uchun ko'rsatiladi.",
        contact: "Bog'lanish",
        usefulLinks: "Foydali havolalar",
        aboutUs: "Biz haqimizda",
        hotelList: "Mehmonxonalar ro'yxati",
        guide: "Qo'llanma",
        privacyPolicy: "Maxfiylik siyosati",
        allRightsReserved: "Barcha huquqlar himoyalangan.",
        login: "Kirish",
    },
    ru: {
        title: "Рейтинг Отелей Узбекистана",
        rateHotel: "Оценить отель",
        info: "Информация",
        oneTimeKey: "Одноразовый ключ",
        enterKey: "Введите ключ",
        verify: "Подтвердить",
        note: "Примечание",
        noteText: "При выезде из отеля вам выдается одноразовый ключ. С помощью этого ключа вы можете оценить отель.",
        rateCategories: "Оцените отель",
        roomCleanliness: "Чистота номера",
        service: "Обслуживание",
        comfort: "Комфорт",
        food: "Питание",
        valueForMoney: "Соотношение цена/качество",
        comment: "Комментарий (необязательно)",
        commentPlaceholder: "Напишите свое мнение об отеле...",
        cancel: "Отмена",
        submit: "Отправить",
        aboutRating: "О системе рейтинга",
        howItWorks: "Как работает система рейтинга отелей Узбекистана",
        ratingProcess: "Процесс оценки",
        ratingProcessDesc:
            "При выезде из отеля вам выдается специальный одноразовый ключ. С помощью этого ключа вы можете оценить отель. Каждый клиент имеет право на одну оценку.",
        ratingCriteria: "Критерии оценки",
        ratingCriteriaDesc:
            "Вы можете оценить отель звездами от 1 до 5. Также вы можете оставить дополнительный комментарий.",
        results: "Результаты",
        resultsDesc: "Все результаты оценки используются для повышения качества отелей и показываются другим клиентам.",
        contact: "Контакты",
        usefulLinks: "Полезные ссылки",
        aboutUs: "О нас",
        hotelList: "Список отелей",
        guide: "Руководство",
        privacyPolicy: "Политика конфиденциальности",
        allRightsReserved: "Все права защищены.",
        login: "Войти",
    },
    en: {
        title: "Uzbekistan Hotel Rating",
        rateHotel: "Rate Hotel",
        info: "Information",
        oneTimeKey: "One-time Key",
        enterKey: "Enter key",
        verify: "Verify",
        note: "Note",
        noteText:
            "When checking out of the hotel, you will be given a one-time key. You can use this key to rate the hotel.",
        rateCategories: "Rate the Hotel",
        roomCleanliness: "Room Cleanliness",
        service: "Service",
        comfort: "Comfort",
        food: "Food",
        valueForMoney: "Value for Money",
        comment: "Comment (optional)",
        commentPlaceholder: "Write your opinion about the hotel...",
        cancel: "Cancel",
        submit: "Submit",
        aboutRating: "About the Rating System",
        howItWorks: "How the Uzbekistan hotel rating system works",
        ratingProcess: "Rating Process",
        ratingProcessDesc:
            "When checking out of the hotel, you will be given a special one-time key. You can use this key to rate the hotel. Each customer has the right to rate once.",
        ratingCriteria: "Rating Criteria",
        ratingCriteriaDesc: "You can rate the hotel with stars from 1 to 5. You can also leave an additional comment.",
        results: "Results",
        resultsDesc: "All rating results are used to improve hotel quality and are shown to other customers.",
        contact: "Contact",
        usefulLinks: "Useful Links",
        aboutUs: "About Us",
        hotelList: "Hotel List",
        guide: "Guide",
        privacyPolicy: "Privacy Policy",
        allRightsReserved: "All rights reserved.",
        login: "Login",
    },
}